name: "Commit Name Validator"
description: "Validates that all commits in a PR follow the format [QD-{number}] {message}. Posts PR comments for violations."
author: "EnsembleIP"

inputs:
  github-token:
    description: "GitHub token used to post PR comments and fetch commits."
    required: false
    default: ${{ github.token }}
  comment-marker:
    description: "HTML comment marker to identify comments created by this action."
    required: false
    default: "<!-- commit-name-action -->"
  commit-pattern:
    description: "Regular expression pattern for validating commit message format."
    required: false
    default: "^\\[QD-\\d+\\] .+"

runs:
  using: "composite"
  steps:
    - name: Validate commit names
      uses: actions/github-script@v7
      env:
        COMMENT_MARKER: ${{ inputs.comment-marker }}
        COMMIT_PATTERN: ${{ inputs.commit-pattern }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const marker = process.env.COMMENT_MARKER;
          const pattern = new RegExp(process.env.COMMIT_PATTERN);
          
          // Skip if not a pull request event
          if (!context.payload.pull_request) {
            core.info("Not a pull request event, skipping commit name validation.");
            return;
          }
          
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const prNumber = context.payload.pull_request.number;
          
          // Fetch all commits in the PR
          core.info(`Fetching commits for PR #${prNumber}...`);
          const { data: commits } = await github.rest.pulls.listCommits({
            owner,
            repo,
            pull_number: prNumber,
            per_page: 100
          });
          
          core.info(`Found ${commits.length} total commits in PR.`);
          
          // Filter out merge commits
          const nonMergeCommits = commits.filter(commit => {
            const isMerge = commit.parents && commit.parents.length > 1;
            const messageStartsWithMerge = commit.commit.message.startsWith("Merge");
            return !isMerge && !messageStartsWithMerge;
          });
          
          core.info(`Validating ${nonMergeCommits.length} non-merge commits...`);
          
          // Validate commit messages against the pattern
          const invalidCommits = [];
          
          for (const commit of nonMergeCommits) {
            const message = commit.commit.message;
            const firstLine = message.split('\n')[0];
            
            if (!pattern.test(firstLine)) {
              invalidCommits.push({
                sha: commit.sha.substring(0, 7),
                fullSha: commit.sha,
                message: firstLine
              });
            }
          }
          
          // Find existing comment from this action
          const { data: comments } = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number: prNumber
          });
          
          const existingComment = comments.find(comment => 
            comment.body && comment.body.includes(marker)
          );
          
          if (invalidCommits.length === 0) {
            core.info("✅ All commits follow the required naming format!");
            
            // Delete existing comment if present
            if (existingComment) {
              core.info("Removing previous failure comment...");
              await github.rest.issues.deleteComment({
                owner,
                repo,
                comment_id: existingComment.id
              });
              core.info("Previous failure comment removed.");
            }
            
            return; // Success
          }
          
          // Build failure message
          core.warning(`❌ Found ${invalidCommits.length} commit(s) with invalid names.`);
          
          const commitList = invalidCommits.map(c => 
            `- \`${c.sha}\`: ${c.message}`
          ).join('\n');
          
          const commentBody = `${marker}
## ❌ Commit Name Validation Failed

The following commit(s) do not follow the required format \`[QD-{issue-key}] {message}\`:

${commitList}

**Required format**: \`[QD-123] Your commit message here\`

Please update the commit messages to follow the required format. You can use:
\`\`\`bash
git rebase -i HEAD~n  # where n is the number of commits to edit
# Then use 'reword' to change commit messages
\`\`\`

---
*Note: Merge commits are automatically excluded from this validation.*`;
          
          // Create or update comment
          if (existingComment) {
            core.info("Updating existing failure comment...");
            await github.rest.issues.updateComment({
              owner,
              repo,
              comment_id: existingComment.id,
              body: commentBody
            });
            core.info("Existing comment updated.");
          } else {
            core.info("Creating new failure comment...");
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: commentBody
            });
            core.info("New comment created.");
          }
          
          // Fail the action
          core.setFailed(`${invalidCommits.length} commit(s) do not follow the required naming format [QD-{issue-key}] {message}`);
